//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: data.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Frametracking_FrameTrackingServiceClient`, then call methods of this protocol to make API calls.
internal protocol Frametracking_FrameTrackingServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? { get }

  func streamFrameUpdates(
    _ request: Frametracking_FrameUpdate,
    callOptions: CallOptions?,
    handler: @escaping (Frametracking_FrameUpdate) -> Void
  ) -> ServerStreamingCall<Frametracking_FrameUpdate, Frametracking_FrameUpdate>
}

extension Frametracking_FrameTrackingServiceClientProtocol {
  internal var serviceName: String {
    return "frametracking.FrameTrackingService"
  }

  /// Server streaming call to streamFrameUpdates
  ///
  /// - Parameters:
  ///   - request: Request to send to streamFrameUpdates.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func streamFrameUpdates(
    _ request: Frametracking_FrameUpdate,
    callOptions: CallOptions? = nil,
    handler: @escaping (Frametracking_FrameUpdate) -> Void
  ) -> ServerStreamingCall<Frametracking_FrameUpdate, Frametracking_FrameUpdate> {
    return self.makeServerStreamingCall(
      path: Frametracking_FrameTrackingServiceClientMetadata.Methods.streamFrameUpdates.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makestreamFrameUpdatesInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Frametracking_FrameTrackingServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Frametracking_FrameTrackingServiceNIOClient")
internal final class Frametracking_FrameTrackingServiceClient: Frametracking_FrameTrackingServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the frametracking.FrameTrackingService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Frametracking_FrameTrackingServiceNIOClient: Frametracking_FrameTrackingServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the frametracking.FrameTrackingService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Frametracking_FrameTrackingServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? { get }

  func makeStreamFrameUpdatesCall(
    _ request: Frametracking_FrameUpdate,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Frametracking_FrameUpdate, Frametracking_FrameUpdate>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Frametracking_FrameTrackingServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Frametracking_FrameTrackingServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeStreamFrameUpdatesCall(
    _ request: Frametracking_FrameUpdate,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Frametracking_FrameUpdate, Frametracking_FrameUpdate> {
    return self.makeAsyncServerStreamingCall(
      path: Frametracking_FrameTrackingServiceClientMetadata.Methods.streamFrameUpdates.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makestreamFrameUpdatesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Frametracking_FrameTrackingServiceAsyncClientProtocol {
  internal func streamFrameUpdates(
    _ request: Frametracking_FrameUpdate,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Frametracking_FrameUpdate> {
    return self.performAsyncServerStreamingCall(
      path: Frametracking_FrameTrackingServiceClientMetadata.Methods.streamFrameUpdates.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makestreamFrameUpdatesInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Frametracking_FrameTrackingServiceAsyncClient: Frametracking_FrameTrackingServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Frametracking_FrameTrackingServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'streamFrameUpdates'.
  func makestreamFrameUpdatesInterceptors() -> [ClientInterceptor<Frametracking_FrameUpdate, Frametracking_FrameUpdate>]
}

internal enum Frametracking_FrameTrackingServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "FrameTrackingService",
    fullName: "frametracking.FrameTrackingService",
    methods: [
      Frametracking_FrameTrackingServiceClientMetadata.Methods.streamFrameUpdates,
    ]
  )

  internal enum Methods {
    internal static let streamFrameUpdates = GRPCMethodDescriptor(
      name: "streamFrameUpdates",
      path: "/frametracking.FrameTrackingService/streamFrameUpdates",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Frametracking_FrameTrackingServiceProvider: CallHandlerProvider {
  var interceptors: Frametracking_FrameTrackingServiceServerInterceptorFactoryProtocol? { get }

  func streamFrameUpdates(request: Frametracking_FrameUpdate, context: StreamingResponseCallContext<Frametracking_FrameUpdate>) -> EventLoopFuture<GRPCStatus>
}

extension Frametracking_FrameTrackingServiceProvider {
  internal var serviceName: Substring {
    return Frametracking_FrameTrackingServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "streamFrameUpdates":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Frametracking_FrameUpdate>(),
        responseSerializer: ProtobufSerializer<Frametracking_FrameUpdate>(),
        interceptors: self.interceptors?.makestreamFrameUpdatesInterceptors() ?? [],
        userFunction: self.streamFrameUpdates(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Frametracking_FrameTrackingServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Frametracking_FrameTrackingServiceServerInterceptorFactoryProtocol? { get }

  func streamFrameUpdates(
    request: Frametracking_FrameUpdate,
    responseStream: GRPCAsyncResponseStreamWriter<Frametracking_FrameUpdate>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Frametracking_FrameTrackingServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Frametracking_FrameTrackingServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Frametracking_FrameTrackingServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Frametracking_FrameTrackingServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "streamFrameUpdates":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Frametracking_FrameUpdate>(),
        responseSerializer: ProtobufSerializer<Frametracking_FrameUpdate>(),
        interceptors: self.interceptors?.makestreamFrameUpdatesInterceptors() ?? [],
        wrapping: { try await self.streamFrameUpdates(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Frametracking_FrameTrackingServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'streamFrameUpdates'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makestreamFrameUpdatesInterceptors() -> [ServerInterceptor<Frametracking_FrameUpdate, Frametracking_FrameUpdate>]
}

internal enum Frametracking_FrameTrackingServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "FrameTrackingService",
    fullName: "frametracking.FrameTrackingService",
    methods: [
      Frametracking_FrameTrackingServiceServerMetadata.Methods.streamFrameUpdates,
    ]
  )

  internal enum Methods {
    internal static let streamFrameUpdates = GRPCMethodDescriptor(
      name: "streamFrameUpdates",
      path: "/frametracking.FrameTrackingService/streamFrameUpdates",
      type: GRPCCallType.serverStreaming
    )
  }
}
